name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.14.1'  # Adjust the Node.js version as needed

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.2.0  # Replace with the desired pnpm version

      - name: Install dependencies
        run: pnpm install

      - name: Build the site
        run: pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist # Adjust this to the correct output directory of your build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v1

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: github-pages
          path: ./dist # Ensure this matches the path used in the upload step
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4